#!/bin/bash

cd locale
for filename in *.po
do
  echo $filename
  cp $filename temp.po
  msgcat -i temp.po > temp2.po
  grep -v "^#~" temp2.po > temp2a.po
  potool -n pcmt temp2a.po > temp3.po
  msgcat -i temp3.po -s > $filename
  rm temp.po temp2.po temp3.po
done;
cd ..
